console.log(String(123));
console.log(String(true));
console.log(String(null));
console.log(String(undefined));
console.log(Number("123"));
console.log(Number("abc"));
console.log(Number(true));
console.log(Number(false));
console.log(Number(null)); 
console.log(Number(undefined)); 
console.log("5" - 3);
console.log("5" + 3); 
console.log(true + 1);
let str = "123";
let num = Number(str);
console.log(num); 
console.log(typeof num);
let num = 123;
let str = String(num);
console.log(str);
console.log(typeof str); 